name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'composer.json'
      - 'phpstan.neon'
      - 'phpstan-baseline.neon'
      - '.github/workflows/phpstan.yml'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, redis, protobuf, grpc
          coverage: none
          extensions: otel_instrumentation-open-telemetry/opentelemetry-php-instrumentation@main

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
